### ISSUE TITLE
Control keeps loading

### ISSUE THREAD

**Issue by davesmits** [edtro/EdTro.AzureDevOps.Extensions.parentdetailscontrol#1]
first of all: an awesome extension! the idea is really neat.. only not getting it to work:

![image](https://user-images.githubusercontent.com/3148438/128256083-69828c10-aea1-4795-b74d-aabd196a7236.png)

In the developer toolbar been able to find this:

TypeError: Cannot read property 'split' of undefined
    at v.initControl (https://realdolmen.gallerycdn.vsassets.io/extensions/realdolmen/edtro-azuredevops-extensions-parentdetailscontrol-public/0.21005.4/1609867383389/index.pdc.bundle.js:1:8767)
    at v.<anonymous> (https://realdolmen.gallerycdn.vsassets.io/extensions/realdolmen/edtro-azuredevops-extensions-parentdetailscontrol-public/0.21005.4/1609867383389/index.pdc.bundle.js:1:8024)
    at Generator.next (<anonymous>)
    at https://realdolmen.gallerycdn.vsassets.io/extensions/realdolmen/edtro-azuredevops-extensions-parentdetailscontrol-public/0.21005.4/1609867383389/index.pdc.bundle.js:1:4263
    at new Promise (<anonymous>)
    at a (https://realdolmen.gallerycdn.vsassets.io/extensions/realdolmen/edtro-azuredevops-extensions-parentdetailscontrol-public/0.21005.4/1609867383389/index.pdc.bundle.js:1:4008)
    at Object.onLoaded (https://realdolmen.gallerycdn.vsassets.io/extensions/realdolmen/edtro-azuredevops-extensions-parentdetailscontrol-public/0.21005.4/1609867383389/index.pdc.bundle.js:1:7956)
    at Object.proxyFunctions.<computed> [as proxy2] (https://realdolmen.gallerycdn.vsassets.io/extensions/realdolmen/edtro-azuredevops-extensions-parentdetailscontrol-public/0.21005.4/1609867383389/js/commons-1f21e238.pdc.bundle.js:1:6114)
    at e.invokeMethod (https://realdolmen.gallerycdn.vsassets.io/extensions/realdolmen/edtro-azuredevops-extensions-parentdetailscontrol-public/0.21005.4/1609867383389/js/commons-1f21e238.pdc.bundle.js:1:3065)
    at e.onMessage (https://realdolmen.gallerycdn.vsassets.io/extensions/realdolmen/edtro-azuredevops-extensions-parentdetailscontrol-public/0.21005.4/1609867383389/js/commons-1f21e238.pdc.bundle.js:1:3803)

any idea?

**Comment by davesmits** [comment]
never mind in one place didnt add a value for "Choose the fields that have to be displayed"

**Comment by edtro** [comment]
@davesmits 
Dear Dave,
Thanks for taking interest in this extension, highly appreciated!

I think I have to implement a fix to show a better/meaningfull error when this property isn't filled in.
Thanks for reporting this issue.

Kr
Edward

**Comment by oriacct** [comment]
Issue is persiting:
![image](https://user-images.githubusercontent.com/4378130/185465327-fb17f4ee-fb6d-4cd2-9973-8d5ce5229b8d.png)
